application: scottkampsduac
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: blog.app

- url: /static
  static_dir: static
  
- url: /ascii
  script: ascii.app

- url: /.*
  script: blog.app


# - url: /blog
#   script: blog.app

# - url: /signup
#   script: blog.app

# - url: /signup/.*
#   script: signup.app  

# - url: /blog/.*
#   script: blog.app

# - url: /sign
#   script: sign.app

# - url: /login
#   script: signup.app

# - url: /logout
#   script: signup.app

# - url: /welcome
#   script: signup.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"

- name: PIL
  version: "1.1.7"